name: CI

on:
  pull_request:
    paths:
      - '**/*.scala'
      - '**/*.sbt'
      - '.scalafmt.conf'
      - 'project/**'
      - '.github/workflows/ci.yaml'

env:
  SBT_OPTS: "-Xmx2G -XX:+UseG1GC -Xss2M"
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9
      - run: sbt scalafmtCheckAll
      - run: sbt headerCheckAll

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9
      - name: Run tests
        run: sbt clean test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-results
