name: Docker CI

on:
  pull_request:
    paths:
      - .github/workflows/docker-ci.yaml
      - build.sbt

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9
      - name: Build Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
        run: sbt docker/Docker/publishLocal
