name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"

env:
  GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES }}

jobs:
  publish-jars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.9.9
    - name: publish
      run: sbt clean publish
  publish-docker-image:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.9.9
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.WRITE_PACKAGES }}
        logout: false
    - name: publish docker images
      run: sbt docker/Docker/publish
  gh-release:
    needs: [publish-jars, publish-docker-image]
    runs-on: self-hosted
    steps:
    - uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.RAW_CI_PAT }}
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}
        tag_name: ${{ github.ref_name }}
